language: php

php:
  - 5.6
  - 5.5
  - hhvm

before_script:
  - composer install --prefer-dist --dev

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script:
  - phpunit --coverage-clover=coverage.clover
